#let hamnosys(..args,body) = {
    text(font: "HamNoSysUnicode",..args, body)
}

// Handshapes
#let hamfist = text(font: "HamNoSysUnicode","\u{e000}")
#let hamflathand = text(font: "HamNoSysUnicode","\u{e001}")
#let hamfinger2 = text(font: "HamNoSysUnicode","\u{e002}")
#let hamfingertwo = text(font: "HamNoSysUnicode","\u{e002}")
#let hamfinger23 = text(font: "HamNoSysUnicode","\u{e003}")
#let hamfingertwothree = text(font: "HamNoSysUnicode","\u{e003}")
#let hamfinger23spread = text(font: "HamNoSysUnicode","\u{e004}")
#let hamfingertwothreespread = text(font: "HamNoSysUnicode","\u{e004}")
#let hamfinger2345 = text(font: "HamNoSysUnicode","\u{e005}")
#let hamfingertwothreefourfive = text(font: "HamNoSysUnicode","\u{e005}")
#let hampinch12 = text(font: "HamNoSysUnicode","\u{e006}")
#let hampinchonetwo = text(font: "HamNoSysUnicode","\u{e006}")
#let hampinchall = text(font: "HamNoSysUnicode","\u{e007}")
#let hampinch12open = text(font: "HamNoSysUnicode","\u{e008}")
#let hamcee12 = text(font: "HamNoSysUnicode","\u{e009}")
#let hamceeonetwo = text(font: "HamNoSysUnicode","\u{e009}")
#let hamceeall = text(font: "HamNoSysUnicode","\u{e00a}")
#let hamceeopen = text(font: "HamNoSysUnicode","\u{e00b}")

// Handshape modifiers
#let hamthumboutmod = text(font: "HamNoSysUnicode","\u{e00c}")
#let hamthumbacrossmod = text(font: "HamNoSysUnicode","\u{e00d}")
#let hamthumbopenmod = text(font: "HamNoSysUnicode","\u{e00e}")
#let hamfingerstraightmod = text(font: "HamNoSysUnicode","\u{e010}")
#let hamfingerbendmod = text(font: "HamNoSysUnicode","\u{e011}")
#let hamfingerhookmod = text(font: "HamNoSysUnicode","\u{e012}")
#let hamdoublebent = text(font: "HamNoSysUnicode","\u{e013}")
#let hamdoublehooked = text(font: "HamNoSysUnicode","\u{e014}")

// Extended finger directions
#let hamextfingeru = text(font: "HamNoSysUnicode","\u{e020}")
#let hamextfingerur = text(font: "HamNoSysUnicode","\u{e021}")
#let hamextfingerr = text(font: "HamNoSysUnicode","\u{e022}")
#let hamextfingerdr = text(font: "HamNoSysUnicode","\u{e023}")
#let hamextfingerd = text(font: "HamNoSysUnicode","\u{e024}")
#let hamextfingerdl = text(font: "HamNoSysUnicode","\u{e025}")
#let hamextfingerl = text(font: "HamNoSysUnicode","\u{e026}")
#let hamextfingerul = text(font: "HamNoSysUnicode","\u{e027}")
#let hamextfingerol = text(font: "HamNoSysUnicode","\u{e028}")
#let hamextfingero = text(font: "HamNoSysUnicode","\u{e029}")
#let hamextfingeror = text(font: "HamNoSysUnicode","\u{e02a}")
#let hamextfingeril = text(font: "HamNoSysUnicode","\u{e02b}")
#let hamextfingeri = text(font: "HamNoSysUnicode","\u{e02c}")
#let hamextfingerir = text(font: "HamNoSysUnicode","\u{e02d}")
#let hamextfingerui = text(font: "HamNoSysUnicode","\u{e02e}")
#let hamextfingerdi = text(font: "HamNoSysUnicode","\u{e02f}")
#let hamextfingerdo = text(font: "HamNoSysUnicode","\u{e030}")
#let hamextfingeruo = text(font: "HamNoSysUnicode","\u{e031}")

// Palm orientation
#let hampalmu = text(font: "HamNoSysUnicode","\u{e038}")
#let hampalmur = text(font: "HamNoSysUnicode","\u{e039}")
#let hampalmr = text(font: "HamNoSysUnicode","\u{e03a}")
#let hampalmdr = text(font: "HamNoSysUnicode","\u{e03b}")
#let hampalmd = text(font: "HamNoSysUnicode","\u{e03c}")
#let hampalmdl = text(font: "HamNoSysUnicode","\u{e03d}")
#let hampalml = text(font: "HamNoSysUnicode","\u{e03e}")
#let hampalmul = text(font: "HamNoSysUnicode","\u{e03f}")

// Location
#let hamhead = text(font: "HamNoSysUnicode","\u{e040}")
#let hamheadtop = text(font: "HamNoSysUnicode","\u{e041}")
#let hamforehead = text(font: "HamNoSysUnicode","\u{e042}")
#let hameyebrows = text(font: "HamNoSysUnicode","\u{e043}")
#let hameyes = text(font: "HamNoSysUnicode","\u{e044}")
#let hamnose = text(font: "HamNoSysUnicode","\u{e045}")
#let hamnostrils = text(font: "HamNoSysUnicode","\u{e046}")
#let hamear = text(font: "HamNoSysUnicode","\u{e047}")
#let hamearlobe = text(font: "HamNoSysUnicode","\u{e048}")
#let hamcheek = text(font: "HamNoSysUnicode","\u{e049}")
#let hamlips = text(font: "HamNoSysUnicode","\u{e04a}")
#let hamtongue = text(font: "HamNoSysUnicode","\u{e04b}")
#let hamteeth = text(font: "HamNoSysUnicode","\u{e04c}")
#let hamchin = text(font: "HamNoSysUnicode","\u{e04d}")
#let hamunderchin = text(font: "HamNoSysUnicode","\u{e04e}")
#let hamneck = text(font: "HamNoSysUnicode","\u{e04f}")
#let hamshouldertop = text(font: "HamNoSysUnicode","\u{e050}")
#let hamshoulders = text(font: "HamNoSysUnicode","\u{e051}")
#let hamchest = text(font: "HamNoSysUnicode","\u{e052}")
#let hamstomach = text(font: "HamNoSysUnicode","\u{e053}")
#let hambelowstomach = text(font: "HamNoSysUnicode","\u{e054}")
#let hamneutralspace = text(font: "HamNoSysUnicode","\u{e05f}")
#let hamupperarm = text(font: "HamNoSysUnicode","\u{e060}")
#let hamelbow = text(font: "HamNoSysUnicode","\u{e061}")
#let hamelbowinside = text(font: "HamNoSysUnicode","\u{e062}")
#let hamlowerarm = text(font: "HamNoSysUnicode","\u{e063}")
#let hamwristback = text(font: "HamNoSysUnicode","\u{e064}")
#let hamwristpulse = text(font: "HamNoSysUnicode","\u{e065}")
#let hamthumbball = text(font: "HamNoSysUnicode","\u{e066}")
#let hampalm = text(font: "HamNoSysUnicode","\u{e067}")
#let hamhandback = text(font: "HamNoSysUnicode","\u{e068}")
#let hamthumbside = text(font: "HamNoSysUnicode","\u{e069}")
#let hampinkyside = text(font: "HamNoSysUnicode","\u{e06a}")
#let hamthumb = text(font: "HamNoSysUnicode","\u{e070}")
#let hamindexfinger = text(font: "HamNoSysUnicode","\u{e071}")
#let hammiddlefinger = text(font: "HamNoSysUnicode","\u{e072}")
#let hamringfinger = text(font: "HamNoSysUnicode","\u{e073}")
#let hampinky = text(font: "HamNoSysUnicode","\u{e074}")
#let hamfingertip = text(font: "HamNoSysUnicode","\u{e075}")
#let hamfingernail = text(font: "HamNoSysUnicode","\u{e076}")
#let hamfingerpad = text(font: "HamNoSysUnicode","\u{e077}")
#let hamfingermidjoint = text(font: "HamNoSysUnicode","\u{e078}")
#let hamfingerbase = text(font: "HamNoSysUnicode","\u{e079}")
#let hamfingerside = text(font: "HamNoSysUnicode","\u{e07a}")

// Location modifiers
#let hamlrbeside = text(font: "HamNoSysUnicode","\u{e058}")
#let hamlrat = text(font: "HamNoSysUnicode","\u{e059}")
#let hamcoreftag = text(font: "HamNoSysUnicode","\u{e05a}")
#let hamcorefref = text(font: "HamNoSysUnicode","\u{e05b}")

// Movement
#let hammoveu = text(font: "HamNoSysUnicode","\u{e080}")
#let hammoveur = text(font: "HamNoSysUnicode","\u{e081}")
#let hammover = text(font: "HamNoSysUnicode","\u{e082}")
#let hammovedr = text(font: "HamNoSysUnicode","\u{e083}")
#let hammoved = text(font: "HamNoSysUnicode","\u{e084}")
#let hammovedl = text(font: "HamNoSysUnicode","\u{e085}")
#let hammovel = text(font: "HamNoSysUnicode","\u{e086}")
#let hammoveul = text(font: "HamNoSysUnicode","\u{e087}")
#let hammoveol = text(font: "HamNoSysUnicode","\u{e088}")
#let hammoveo = text(font: "HamNoSysUnicode","\u{e089}")
#let hammoveor = text(font: "HamNoSysUnicode","\u{e08a}")
#let hammoveil = text(font: "HamNoSysUnicode","\u{e08b}")
#let hammovei = text(font: "HamNoSysUnicode","\u{e08c}")
#let hammoveir = text(font: "HamNoSysUnicode","\u{e08d}")
#let hammoveui = text(font: "HamNoSysUnicode","\u{e08e}")
#let hammovedi = text(font: "HamNoSysUnicode","\u{e08f}")
#let hammovedo = text(font: "HamNoSysUnicode","\u{e090}")
#let hammoveuo = text(font: "HamNoSysUnicode","\u{e091}")
#let hamcircleo = text(font: "HamNoSysUnicode","\u{e092}")
#let hamcirclei = text(font: "HamNoSysUnicode","\u{e093}")
#let hamcircled = text(font: "HamNoSysUnicode","\u{e094}")
#let hamcircleu = text(font: "HamNoSysUnicode","\u{e095}")
#let hamcirclel = text(font: "HamNoSysUnicode","\u{e096}")
#let hamcircler = text(font: "HamNoSysUnicode","\u{e097}")
#let hamcircleul = text(font: "HamNoSysUnicode","\u{e098}")
#let hamcircledr = text(font: "HamNoSysUnicode","\u{e099}")
#let hamcircleur = text(font: "HamNoSysUnicode","\u{e09a}")
#let hamcircledl = text(font: "HamNoSysUnicode","\u{e09b}")
#let hamcircleol = text(font: "HamNoSysUnicode","\u{e09c}")
#let hamcircleir = text(font: "HamNoSysUnicode","\u{e09d}")
#let hamcircleor = text(font: "HamNoSysUnicode","\u{e09e}")
#let hamcircleil = text(font: "HamNoSysUnicode","\u{e09f}")
#let hamcircleui = text(font: "HamNoSysUnicode","\u{e0a0}")
#let hamcircledo = text(font: "HamNoSysUnicode","\u{e0a1}")
#let hamcircleuo = text(font: "HamNoSysUnicode","\u{e0a2}")
#let hamcircledi = text(font: "HamNoSysUnicode","\u{e0a3}")
#let hamfingerplay = text(font: "HamNoSysUnicode","\u{e0a4}")
#let hamnodding = text(font: "HamNoSysUnicode","\u{e0a5}")
#let hamswinging = text(font: "HamNoSysUnicode","\u{e0a6}")
#let hamtwisting = text(font: "HamNoSysUnicode","\u{e0a7}")
#let hamstircw = text(font: "HamNoSysUnicode","\u{e0a8}")
#let hamstirccw = text(font: "HamNoSysUnicode","\u{e0a9}")
#let hamreplace = text(font: "HamNoSysUnicode","\u{e0aa}")
#let hamnomotion = text(font: "HamNoSysUnicode","\u{e0af}")
#let hamclocku = text(font: "HamNoSysUnicode","\u{e0b0}")
#let hamclockul = text(font: "HamNoSysUnicode","\u{e0b1}")
#let hamclockl = text(font: "HamNoSysUnicode","\u{e0b2}")
#let hamclockdl = text(font: "HamNoSysUnicode","\u{e0b3}")
#let hamclockd = text(font: "HamNoSysUnicode","\u{e0b4}")
#let hamclockdr = text(font: "HamNoSysUnicode","\u{e0b5}")
#let hamclockr = text(font: "HamNoSysUnicode","\u{e0b6}")
#let hamclockur = text(font: "HamNoSysUnicode","\u{e0b7}")
#let hamclockfull = text(font: "HamNoSysUnicode","\u{e0b8}")
#let hamarcl = text(font: "HamNoSysUnicode","\u{e0b9}")
#let hamarcu = text(font: "HamNoSysUnicode","\u{e0ba}")
#let hamarcr = text(font: "HamNoSysUnicode","\u{e0bb}")
#let hamarcd = text(font: "HamNoSysUnicode","\u{e0bc}")
#let hamwavy = text(font: "HamNoSysUnicode","\u{e0bd}")
#let hamzigzag = text(font: "HamNoSysUnicode","\u{e0be}")
#let hamellipseh = text(font: "HamNoSysUnicode","\u{e0c0}")
#let hamellipseur = text(font: "HamNoSysUnicode","\u{e0c1}")
#let hamellipsev = text(font: "HamNoSysUnicode","\u{e0c2}")
#let hameelipseul = text(font: "HamNoSysUnicode","\u{e0c3}")
#let hamincreasing = text(font: "HamNoSysUnicode","\u{e0c4}")
#let hamdecreasing = text(font: "HamNoSysUnicode","\u{e0c5}")
#let hamfast = text(font: "HamNoSysUnicode","\u{e0c8}")
#let hamslow = text(font: "HamNoSysUnicode","\u{e0c9}")
#let hamtense = text(font: "HamNoSysUnicode","\u{e0ca}")
#let hamrest = text(font: "HamNoSysUnicode","\u{e0cb}")
#let hamhalt = text(font: "HamNoSysUnicode","\u{e0cc}")
#let hamclose = text(font: "HamNoSysUnicode","\u{e0d0}")
#let hamtouch = text(font: "HamNoSysUnicode","\u{e0d1}")
#let haminterlock = text(font: "HamNoSysUnicode","\u{e0d2}")
#let hamcross = text(font: "HamNoSysUnicode","\u{e0d3}")
#let hamarmextended = text(font: "HamNoSysUnicode","\u{e0d4}")
#let hambehind = text(font: "HamNoSysUnicode","\u{e0d5}")
#let hambrushing = text(font: "HamNoSysUnicode","\u{e0d6}")

// Movement modifiers
#let hamsmallmod = text(font: "HamNoSysUnicode","\u{e0c6}")
#let hamlargemod = text(font: "HamNoSysUnicode","\u{e0c7}")

// Other symbols
#let hamrepeatfromstart = text(font: "HamNoSysUnicode","\u{e0d8}")
#let hamrepeatfromstartseveral = text(font: "HamNoSysUnicode","\u{e0d9}")
#let hamrepeatcontinue = text(font: "HamNoSysUnicode","\u{e0da}")
#let hamrepeatcontinueseveral = text(font: "HamNoSysUnicode","\u{e0db}")
#let hamrepeatreverse = text(font: "HamNoSysUnicode","\u{e0dc}")
#let hamalternatingmotion = text(font: "HamNoSysUnicode","\u{e0dd}")
#let hamseqbegin = text(font: "HamNoSysUnicode","\u{e0e0}")
#let hamseqend = text(font: "HamNoSysUnicode","\u{e0e1}")
#let hamparbegin = text(font: "HamNoSysUnicode","\u{e0e2}")
#let hamparend = text(font: "HamNoSysUnicode","\u{e0e3}")
#let hamfusionbegin = text(font: "HamNoSysUnicode","\u{e0e4}")
#let hamfusionend = text(font: "HamNoSysUnicode","\u{e0e5}")
#let hambetween = text(font: "HamNoSysUnicode","\u{e0e6}")
#let hamplus = text(font: "HamNoSysUnicode","\u{e0e7}")
#let hamsymmpar = text(font: "HamNoSysUnicode","\u{e0e8}")
#let hamsymmlr = text(font: "HamNoSysUnicode","\u{e0e9}")
#let hamnondominant = text(font: "HamNoSysUnicode","\u{e0ea}")
#let hamnonipsi = text(font: "HamNoSysUnicode","\u{e0eb}")
#let hametc = text(font: "HamNoSysUnicode","\u{e0ec}")
#let hamorirelative = text(font: "HamNoSysUnicode","\u{e0ed}")
#let hammime = text(font: "HamNoSysUnicode","\u{e0f0}")

// Version symbol
#let hamversion40 = text(font: "HamNoSysUnicode","\u{e0f1}")
#let hamversionfourzerp = text(font: "HamNoSysUnicode","\u{e0f1}")

// Regular Unicode characters
#let hamspace = text(font: "HamNoSysUnicode","\u{0020}")
#let hamexclaim = text(font: "HamNoSysUnicode","\u{0021}")
#let hamcomma = text(font: "HamNoSysUnicode","\u{002c}")
#let hamfullstop = text(font: "HamNoSysUnicode","\u{002e}")
#let hamquery = text(font: "HamNoSysUnicode","\u{003f}")
#let hamaltbegin = text(font: "HamNoSysUnicode","\u{007b}")
#let hammetaalt = text(font: "HamNoSysUnicode","\u{007c}")
#let hamaltend = text(font: "HamNoSysUnicode","\u{007d}")

// Obsolete spacing symbols
#let hamwristtopulse = text(font: "HamNoSysUnicode","\u{e07c}")
#let hamwristtoback = text(font: "HamNoSysUnicode","\u{e07d}")
#let hamwristtothumb = text(font: "HamNoSysUnicode","\u{e07e}")
#let hamwristtopinky = text(font: "HamNoSysUnicode","\u{e07f}")
#let hammovecross = text(font: "HamNoSysUnicode","\u{e0ad}")
#let hammoveX = text(font: "HamNoSysUnicode","\u{e0ae}")